version: '3.9'

services:
  db:
    image: postgres:15
    container_name: contacts_db
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  test_db:
    image: postgres:16
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
      POSTGRES_DB: test_db
    ports:
      - '5433:5432'
    volumes:
      - test_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: contacts_redis
    restart: always
    ports:
      - '6379:6379'

  web:
    build: .
    container_name: contacts_api
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - '8000:8000'
    env_file:
      - .env
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  test:
    build: .
    container_name: contacts_api_tests
    depends_on:
      - test_db
      - redis
    env_file:
      - .env.test
    volumes:
      - .:/app
    command: >
      sh -c "pytest --cov=contacts_api tests/ --disable-warnings --maxfail=2"

volumes:
  pgdata:
  test_pgdata:
